const fs = require('fs');
const path = require('path');

const dir = path.join(__dirname, 'src', 'components');
if (!fs.existsSync(dir)) fs.mkdirSync(dir);

const components = {
  'Header.tsx': `import React from 'react';\nexport default function Header() { return <header className="h-16 border-b border-border bg-card flex items-center px-6 justify-between"><div className="font-bold text-xl flex items-center gap-2"><span className="text-primary">OORJA</span> <span className="text-gray-400 text-sm font-normal">| Energy Supply Chain Resilience</span></div><div className="flex items-center gap-4"><div className="text-sm bg-success/20 text-success px-3 py-1 rounded-full border border-success/30">System Nominal</div><div className="text-sm text-gray-400">Response Latency: 42ms</div></div></header>; }`,
  'RiskMap.tsx': `import React from 'react';\nimport { MapContainer, TileLayer, Marker, Popup, CircleMarker } from 'react-leaflet';\nimport 'leaflet/dist/leaflet.css';\n\nexport default function RiskMap() {\n  return (\n    <MapContainer center={[20, 60]} zoom={4} style={{ height: '100%', width: '100%', background: '#0B0F19' }} zoomControl={false}>\n      <TileLayer\n        url="https://{s}.basemaps.cartocdn.com/dark_all/{z}/{x}/{y}{r}.png"\n        attribution='&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors &copy; <a href="https://carto.com/attributions">CARTO</a>'\n      />\n      {/* Strait of Hormuz */}\n      <CircleMarker center={[26.56, 56.25]} radius={15} pathOptions={{ color: 'red', fillColor: 'red', fillOpacity: 0.4 }}>\n        <Popup>Strait of Hormuz - High Risk (78/100)</Popup>\n      </CircleMarker>\n      {/* Red Sea */}\n      <CircleMarker center={[20, 38]} radius={25} pathOptions={{ color: 'orange', fillColor: 'orange', fillOpacity: 0.3 }}>\n        <Popup>Red Sea / Suez - Medium Risk (65/100)</Popup>\n      </CircleMarker>\n      {/* Refineries - Kandla, Jamnagar */}\n      <CircleMarker center={[23.03, 70.21]} radius={8} pathOptions={{ color: '#10B981', fillColor: '#10B981', fillOpacity: 0.8 }} />\n      <CircleMarker center={[19.07, 72.87]} radius={8} pathOptions={{ color: '#10B981', fillColor: '#10B981', fillOpacity: 0.8 }} />\n    </MapContainer>\n  );\n}`,
  'RiskGauges.tsx': `import React from 'react';\nexport default function RiskGauges() { return <div className="flex h-full gap-4 items-center justify-around"><Gauge title="Hormuz" score={78} /> <Gauge title="Red Sea" score={65} /> <Gauge title="Malacca" score={22} /> <Gauge title="Cape of Good Hope" score={15} /></div>; }\n\nfunction Gauge({title, score}: {title: string, score: number}) {\n  const color = score > 70 ? 'text-danger' : score > 40 ? 'text-warning' : 'text-success';\n  return <div className="flex flex-col items-center"><div className={\`text-4xl font-bold \${color}\`}>{score}</div><div className="text-sm text-gray-400 mt-2">{title}</div></div>;\n}`,
  'ScenarioModeler.tsx': `import React from 'react';\nexport default function ScenarioModeler() { return <div className="flex flex-col gap-2"><select className="bg-background border border-border rounded p-2 text-white"><option>Hormuz Partial Closure (30% drop)</option><option>OPEC+ Emergency Cut</option><option>Red Sea Total Suspension</option></select><div className="mt-4 text-sm text-gray-300">Cascading Impact: <br/><span className="text-danger">- 1.2M bpd shortfall</span><br/><span className="text-warning">- +14% Domestic Fuel Price</span><br/><span className="text-danger">- GDP -0.4%</span></div></div>; }`,
  'ProcurementCards.tsx': `import React from 'react';\nexport default function ProcurementCards() { return <div className="flex flex-col gap-3"><Card source="Russian Urals (East)" eta="14 days" price="$72/bbl" match="94%" /> <Card source="US WTI" eta="28 days" price="$81/bbl" match="88%" /> <Card source="West African Bonny Light" eta="21 days" price="$84/bbl" match="98%" /></div>; }\n\nfunction Card({source, eta, price, match}: any) { return <div className="border border-border rounded bg-background p-3 flex justify-between items-center"><div><div className="font-semibold">{source}</div><div className="text-xs text-gray-400">ETA: {eta} | Match: {match}</div></div><div className="font-bold text-primary">{price}</div></div>; }`,
  'SPRTimeline.tsx': `import React from 'react';\nexport default function SPRTimeline() { return <div className="text-sm"><div className="flex justify-between mb-1"><span>Current SPR</span> <span className="text-warning">9.5 Days</span></div><div className="w-full bg-border h-4 rounded overflow-hidden"><div className="bg-warning h-full" style={{width: '25%'}}></div></div><div className="mt-4">Optimal Drawdown:<br/><span className="text-gray-400">Day 1-5: 200k bpd</span><br/><span className="text-gray-400">Day 6-10: 450k bpd</span></div></div>; }`,
  'AlertFeed.tsx': `import React from 'react';\nimport { Bell } from 'lucide-react';\nexport default function AlertFeed() { return <div className="fixed bottom-4 right-4 bg-card border border-border shadow-lg rounded-lg p-4 w-80 z-50"><div className="flex items-center gap-2 font-bold mb-3 border-b border-border pb-2"><Bell className="w-4 h-4 text-warning"/> Live Intel Feed</div><div className="flex flex-col gap-3 text-xs"><div className="text-gray-300"><span className="text-danger font-bold">[14:02]</span> Missile strike reported near Bab el-Mandeb strait.</div><div className="text-gray-300"><span className="text-warning font-bold">[13:45]</span> VLCC tanker rates spike 12% in Persian Gulf.</div></div></div>; }`
};

for (const [file, content] of Object.entries(components)) {
  fs.writeFileSync(path.join(dir, file), content);
}
console.log('Components created successfully');
